"""Causally valid single-node energy-harvesting sensor environment.

The latent measurement entropy is generated by the environment but is not part
of the pre-decision observation. A full entropy value becomes available only
when the node pays for and executes ``ACTION_SAMPLE``. Policies instead observe
a noisy low-power event proxy whose monitoring cost is charged every step.
"""

from __future__ import annotations

import random
from pathlib import Path
import sys
from typing import Any, Dict, Optional, Tuple

import numpy as np

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

import shared_config
from environment.energy_model import EnergyModel


class SingleAgentSensorEnv:
    """A solar-harvesting node with a causal sensing/action sequence."""

    LOCAL_OBS_DIM = 4  # battery, event proxy, AoI, harvest forecast

    def __init__(
        self,
        scenario: str = "stable",
        high_entropy_threshold: float = shared_config.BASELINE_RULE_ENTROPY_THRESHOLD,
        seed: Optional[int] = None,
        energy_model: Optional[EnergyModel] = None,
        external_event_control: bool = False,
        reward_weights: Optional[Dict[str, float]] = None,
    ):
        if scenario not in shared_config.SCENARIOS:
            raise ValueError(f"Unknown scenario {scenario!r}")
        self.scenario_name = scenario
        self.scenario_cfg = shared_config.SCENARIOS[scenario]
        self.energy_model = energy_model or EnergyModel()
        self.high_entropy_threshold = high_entropy_threshold
        self.episode_length = shared_config.EPISODE_LENGTH_TIMESTEPS
        self.external_event_control = external_event_control
        self.reward_weights = dict(shared_config.REWARD_WEIGHTS)
        if reward_weights:
            self.reward_weights.update(reward_weights)

        self.np_random = np.random.RandomState(seed if seed is not None else shared_config.SEED)
        self.py_random = random.Random(seed if seed is not None else shared_config.SEED)
        self.sunrise_step = int(self.episode_length * 0.25)
        self.sunset_step = int(self.episode_length * 0.75)
        self.cloud_ar1 = self.scenario_cfg.get("cloud_correlation_ar1", 0.70)
        self.cloud_noise_std = self.scenario_cfg.get("cloud_noise_std", 0.015)
        self.event_lambda = self.scenario_cfg.get("event_frequency_lambda", 0.03)
        self.event_decay = self.scenario_cfg.get("event_persistence_decay", 0.50)

        self.battery = 1.0
        self.current_entropy = 0.10  # latent until a sample is executed
        self.event_proxy = 0.10
        self.last_measured_entropy: Optional[float] = None
        self.aoi = 0
        self.timestep = 0
        self.cloud_factor = 1.0
        self._reset_diagnostics()

    def _reset_diagnostics(self) -> None:
        self.total_samples_requested = 0
        self.total_samples_executed = 0
        self.total_rejections = 0
        self.total_missed_events = 0
        self.total_harvested_energy = 0.0
        self.total_consumed_energy = 0.0

    def seed(self, seed: Optional[int] = None) -> None:
        seed = shared_config.SEED if seed is None else seed
        self.np_random = np.random.RandomState(seed)
        self.py_random = random.Random(seed)

    def get_action_mask(self) -> np.ndarray:
        can_sample = int(self.battery >= self.energy_model.sample_energy_cost)
        return np.array([1, can_sample], dtype=np.int8)

    def _update_weather(self) -> float:
        noise = self.np_random.normal(0.0, self.cloud_noise_std)
        self.cloud_factor = float(np.clip(
            self.cloud_ar1 * self.cloud_factor + (1.0 - self.cloud_ar1) + noise,
            0.05,
            1.0,
        ))
        return self.cloud_factor

    def get_harvest_forecast(self, timestep: Optional[int] = None) -> float:
        """Known clear-sky time-of-day envelope, not realised cloud energy."""
        t = self.timestep if timestep is None else timestep
        t %= self.episode_length
        if not self.sunrise_step <= t <= self.sunset_step:
            return 0.0
        progress = (t - self.sunrise_step) / (self.sunset_step - self.sunrise_step)
        return float(np.sin(np.pi * progress))

    def _calculate_solar_harvest(self) -> float:
        if self.get_harvest_forecast() <= 0.0:
            return 0.0
        t = self.timestep % self.episode_length
        progress = (t - self.sunrise_step) / (self.sunset_step - self.sunrise_step)
        return self.energy_model.calculate_harvested_energy(progress, self._update_weather())

    def _update_event_entropy(self) -> float:
        baseline = float(self.np_random.uniform(0.05, 0.18))
        if self.np_random.rand() < self.event_lambda:
            self.current_entropy = max(self.current_entropy, float(self.np_random.uniform(0.75, 1.0)))
        else:
            self.current_entropy = max(baseline, self.current_entropy * self.event_decay)
        return float(np.clip(self.current_entropy, 0.0, 1.0))

    def _generate_event_proxy(self) -> float:
        """Generate a noisy wake-up detector score from the latent phenomenon."""
        is_event = self.current_entropy >= self.high_entropy_threshold
        if is_event:
            detected = self.np_random.rand() >= shared_config.EVENT_PROXY_FALSE_NEGATIVE_RATE
        else:
            detected = self.np_random.rand() < shared_config.EVENT_PROXY_FALSE_POSITIVE_RATE
        centre = 0.80 if detected else 0.20
        self.event_proxy = float(np.clip(
            centre + self.np_random.normal(0.0, shared_config.EVENT_PROXY_NOISE_STD),
            0.0,
            1.0,
        ))
        return self.event_proxy

    def set_external_event_entropy(self, entropy: float) -> None:
        """Set coordinated latent state and derive the corresponding causal proxy."""
        self.current_entropy = float(np.clip(entropy, 0.0, 1.0))
        self._generate_event_proxy()

    def _local_obs(self) -> np.ndarray:
        return np.array([
            self.battery,
            self.event_proxy,
            min(1.0, self.aoi / 50.0),
            self.get_harvest_forecast(),
        ], dtype=np.float32)

    def reset(
        self,
        seed: Optional[int] = None,
        options: Optional[dict] = None,
    ) -> Tuple[np.ndarray, Dict[str, Any]]:
        if seed is not None:
            self.seed(seed)
        self.timestep = 0
        self.aoi = 0
        self.cloud_factor = 1.0
        self.battery = float(self.np_random.uniform(0.10, 0.25)) if self.scenario_cfg.get(
            "initial_battery_low", False
        ) else float(self.np_random.uniform(0.50, 0.90))
        self.current_entropy = float(self.np_random.uniform(0.05, 0.20))
        self.last_measured_entropy = None
        self._generate_event_proxy()
        self._reset_diagnostics()
        return self._local_obs(), {
            "timestep": 0,
            "battery": self.battery,
            "event_proxy": self.event_proxy,
            "aoi": self.aoi,
            "harvest_forecast": self.get_harvest_forecast(),
            "measured_entropy": None,
            "action_mask": self.get_action_mask(),
            "causal_observation": True,
        }

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, bool, Dict[str, Any]]:
        """Evaluate ``a_t`` on latent state ``s_t``, then transition to ``s_(t+1)``."""
        shared_config.validate_contracts(action=action)
        self.timestep += 1

        current_battery = self.battery
        latent_entropy = self.current_entropy
        proxy_at_decision = self.event_proxy
        current_aoi = self.aoi
        is_event = latent_entropy >= self.high_entropy_threshold

        sample_requested = action == shared_config.ACTION_SAMPLE
        sample_executed = sample_requested and current_battery >= self.energy_model.sample_energy_cost
        sample_rejected = sample_requested and not sample_executed
        if sample_requested:
            self.total_samples_requested += 1
        if sample_executed:
            self.total_samples_executed += 1
        if sample_rejected:
            self.total_rejections += 1

        w = self.reward_weights
        components = {
            "capture": w["w_info"] if sample_executed and is_event else 0.0,
            "miss": -w["w_miss"] if (not sample_executed and is_event) else 0.0,
            "sample_energy": -w["w_energy"] if sample_executed else 0.0,
            "aoi": -w["w_aoi"] * min(1.0, current_aoi / 50.0),
            "rejection": -w["w_rejection"] if sample_rejected else 0.0,
        }
        if not sample_executed and is_event:
            self.total_missed_events += 1
        reward = float(sum(components.values()))

        harvested = self._calculate_solar_harvest()
        consumed = self.energy_model.sleep_energy_cost + self.energy_model.proxy_monitor_energy_cost
        if sample_executed:
            consumed += self.energy_model.sample_energy_cost
        self.total_harvested_energy += harvested
        self.total_consumed_energy += consumed
        self.battery = float(np.clip(current_battery - consumed + harvested, 0.0, 1.0))

        self.aoi = 0 if sample_executed else current_aoi + 1
        self.last_measured_entropy = latent_entropy if sample_executed else None

        if not self.external_event_control:
            self._update_event_entropy()
            self._generate_event_proxy()

        terminated = self.timestep >= self.episode_length
        info = {
            "timestep": self.timestep,
            "action_requested": action,
            "action_executed": shared_config.ACTION_SAMPLE if sample_executed else shared_config.ACTION_SLEEP,
            "sample_requested": sample_requested,
            "sample_rejected": sample_rejected,
            "sample_executed": sample_executed,
            "sample_delivered": sample_executed,
            "harvested_energy": harvested,
            "consumed_energy": consumed,
            "battery": self.battery,
            "battery_joules": self.energy_model.normalized_to_joules(self.battery),
            "event_proxy_at_decision": proxy_at_decision,
            "latent_entropy_at_decision": latent_entropy,
            "data_entropy_at_decision": latent_entropy,
            "measured_entropy": self.last_measured_entropy,
            "is_high_entropy": is_event,
            "aoi": self.aoi,
            "harvest_forecast": self.get_harvest_forecast(),
            "reward_components": components,
            "action_mask": self.get_action_mask(),
            "causal_observation": True,
        }
        return self._local_obs(), reward, terminated, False, info
