env: "iot"

env_args:
  scenario: "volatile"
  regime: "independent"
  ablation: "full"
  mask_neighbor_signal: False
  map_name: "iot_sensor"

test_greedy: True
test_nepisode: 10
test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000
t_max: 200000
gamma: 0.95
