env: "iot"

env_args:
  scenario: "volatile"
  map_name: "mock"

test_greedy: True
test_nepisode: 10
test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000
t_max: 200000
gamma: 0.85

